name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  permissions:
    contents: write
    
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: "Release ${{ github.ref_name }}"
        body: |
          🚀 Nueva versión disponible:
          - Mejoras en el rendimiento.
          - Correcciones de errores.
       draft: false
       prerelease: false

